sven/apps/activity/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns('sven.apps.activity.views',
    url(r'^$', 'index', name='index'),
    url(r'^index$', 'index', name='index'),
)

sven/apps/monitor/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns( 'sven.apps.monitor.views',
    url( r'^$', 'index', name='index'),
    url( r'^index$', 'index', name='index'),

    url( r'^locationGroups$', 'locationGroups', name='locationGroups'),

    url( r'^locationGroup/(?P<id>\d+)/$', 'locationGroup', name='locationGroup'),

    url( r'^location/(?P<id>\d+)/$', 'location', name='location'),
    url( r'^location/new/$', 'location', name='locationNew'),

#    url( r'^device/new/(?P<locationId>\d+)/$', 'device', name='deviceNew'),
    url( r'^device/(?P<id>\d+)/$', 'device', name='device'),
    url( r'^device/new/$', 'device', name='deviceNew'),

    url( r'^ajaxListLocationGroups$', 'ajaxListLocationGroups', name='ajaxListLocationGroups'),
    url( r'^ajaxListLocations$', 'ajaxListLocations', name='ajaxListLocations'),
    url( r'^ajaxListDevices$', 'ajaxListDevices', name='ajaxListDevices'),

    url( r'^ajaxUpdateLocationGroup$', 'ajaxUpdateLocationGroup', name='ajaxUpdateLocationGroup'),
    url( r'^ajaxUpdateLocation$', 'ajaxUpdateLocation', name='ajaxUpdateLocation'),
    url( r'^ajaxUpdateDevice$', 'ajaxUpdateDevice', name='ajaxUpdateDevice'),
    url( r'^ajaxUpdateDeviceAction', 'ajaxUpdateDeviceAction', name='ajaxUpdateDeviceAction'),

    url( r'^ajaxInputMatrix', 'ajaxInputMatrix', name='ajaxInputMatrix'),
    url( r'^ajaxLoadWidgets', 'ajaxLoadWidgets', name='ajaxLoadWidgets'),
)

sven/apps/sensors/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns('sven.apps.sensors.views',
    url(r'^$', 'index', name='index'),
    url(r'^index$', 'index', name='index'),
)

sven/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns( '',
    url( r'^admin/',            include( admin.site.urls ) ),

    url( r'^dashboard/',        include( 'sven.apps.dashboard.urls',        namespace = 'dashboard' ) ),
    url( r'^configuration/',    include( 'sven.apps.configuration.urls',    namespace = 'configuration' ) ),
    url( r'^monitor/',          include( 'sven.apps.monitor.urls',          namespace = 'monitor' ) ),

    url( r'^activity/',         include( 'sven.apps.activity.urls',         namespace = 'activity' ) ),
    url( r'^sensors/',          include( 'sven.apps.sensors.urls',          namespace = 'sensors' ) ),
)

sven/apps/activity/models.py
from django.db import models

# Create your models here.

sven/apps/configuration/models.py
from django.db import models

class SvenAbstract( models.Model ):
    created = models.DateTimeField( auto_now_add = True )
    updated = models.DateTimeField( auto_now = True, auto_now_add = True )

    class Meta:
        abstract = True


class SvenAbstractNDA( SvenAbstract ):

    """
    Create Name, Description and Active fields
    """
    name            = models.CharField( max_length = 255, null = True, blank = True )
    description     = models.TextField( null = True, blank = True )
    active          = models.BooleanField( default = True )

    class Meta:
        abstract = True


    def __str__( self ):
        return self.name


class Database_Type( SvenAbstractNDA ):
    pass


class Interface_Type( SvenAbstractNDA ):
    pass


class Interface( SvenAbstractNDA ):
    type                = models.ForeignKey( Interface_Type )
    web_socket_host     = models.CharField( max_length = 128 )
    web_socket_port     = models.IntegerField( )
    daemon_db_type      = models.ForeignKey( Database_Type )
    daemon_db_host      = models.CharField( max_length = 64 )
    daemon_db_port      = models.IntegerField( )
    daemon_db_user      = models.CharField( max_length = 64 )
    daemon_db_pass      = models.CharField( max_length = 64 )

sven/apps/dashboard/models.py
from django.db import models

# Create your models here.

sven/apps/sensors/models.py
from django.db import models

# Create your models here.

sven/libs/display/models.py
from django.db import models

# Create your models here.

sven/libs/management/models.py
from django.db import models

# Create your models here.

sven/apps/activity/views.py
from django.shortcuts import render

def index( request ):
    data = { 'one' : 'elijah', 'two' : 'ethun', 'three' : 'ray' }

    return render( request, 'activity/index.html', { 'datas' : data } )

sven/apps/configuration/views.py
from django.shortcuts import render

# Create your views here.

sven/apps/dashboard/views.py
from django.shortcuts import render

def index( request ):
    data = { 'one' : 'elijah', 'two' : 'ethun', 'three' : 'ray' }

    return render( request, 'dashboard/index.html', { 'datas' : data } )

sven/apps/monitor/views.py
import os
#import json

import time
import string
import logging
import traceback
import simplejson as json

from django.conf import settings
from django.http import Http404
from django.http import HttpResponse
from django.template import RequestContext
from django.views.decorators.csrf import csrf_exempt
from django.shortcuts import render, render_to_response
from django.views.generic import TemplateView
from django.contrib.auth.decorators import login_required
from django import template
from models import *

logger = logging.getLogger(__name__)
register = template.Library()


@register.simple_tag
def template_exists(template_name):
  try:
    template.loader.get_template(template_name)
    return "Template exists"
  except template.TemplateDoesNotExist:
    return "Template doesn't exist"


def svenCommonData(request):
  data = {
    'base_url': request.build_absolute_uri('/')[:-1],
    'menu_items': Location_Group.objects.all().prefetch_related()
  }

  return data


def svenCommonAjaxData(request):
  data = {
    'success': True,
    'message': None,
    'data': {},
    'base_url': request.build_absolute_uri('/')[:-1]
  }

  return data


@csrf_exempt
def index(request):
  return render(request, 'monitor/index.html', svenCommonData(request))


@csrf_exempt
def locationGroups(request):
  return render(request, 'monitor/locationGroups.html', svenCommonData(request))


@csrf_exempt
def locationGroup(request, id):
  location_group = Location_Group.objects.prefetch_related('location_set')\
    .get(pk = id)

  request.session['location_group_id'] = id

  data = svenCommonData(request)
  data['location_group'] = location_group

  return render(request, 'monitor/locationGroup.html', data)


@csrf_exempt
def location(request, id = 'new'):
  location = None

  location_group = Location_Group.objects.get(
    pk = request.session['location_group_id'])

  if id != 'new' and int(id) > 0:
    #
    # Edit operation
    #
    request.session['location_id'] = id
    location = Location.objects.get(pk = id)
#    print location.location_group_id
  elif id != 'new':
    #
    # We can't be here without a location group
    #
    raise Http404()

  data = svenCommonData(request)
  data['location'] = location
  data['location_group'] = location_group

  return render(request, 'monitor/location.html', data)


@csrf_exempt
def device(request, id = 'new'):
  data = svenCommonData(request)

  device = None
  location = Location.objects.get(pk = request.session['location_id'])
  location_group = Location_Group.objects.get(pk = location.location_group_id)

  if id != 'new' and int(id) > 0:
    # Edit operation
    request.session['device_id'] = id
    device = Device.objects.get(pk = id)

    data['device'] = Device.objects.get(pk = id)

    for parameter in Device_Parameter.objects.filter(device = device):
      if parameter.parameter == 'interface':
        data['interface'] = parameter.value

      if parameter.parameter == 'bus':
        data['bus'] = parameter.value

    data['pageTemplate'] = None

    if 'interface' in data and 'bus' in data:
      pageTemplatePath = os.path.abspath(
        os.path.dirname(__file__)) + '/../../templates/monitor/modules/' + data[
                           'interface'] + '/' + data['bus'] + '/index.html'

      if os.path.isfile(pageTemplatePath):
        data['pageTemplate'] = pageTemplatePath

  elif id != 'new':
    # We can't be here without a device id or 'new'
    raise Http404()

  data.update({
    'location_group': location_group,
    'location': location,
  })

  return render(request, 'monitor/device.html', data)


def calculatePercentageComplete(device, module_listing):
  if device is None:
    return 0

  try:
    # calculate the percentage complete
    total = int(len(module_listing[
      'parameters_required'])) + 2 # Remove 2 for 'name' and 'description'
    complete = 0
  except:
    return 0

  logger.info(module_listing['parameters_required'])

  for key in ['name', 'description']:
    if getattr(device, key):
      complete += 1

  try:
    objects = Device_Parameter.objects.filter(
        device = device,
        parameter__in = module_listing['parameters_required'])

    for object in objects:
      if object.value is not None and object.value != '':
        complete += 1
  except:
    pass

  return int(100 * complete / total)


#
# Ajax update methods
#

@csrf_exempt
def ajaxUpdateLocationGroup(request):
  response_data = svenCommonAjaxData(request)

  if request.is_ajax() and request.method == 'POST':
    try:
      p = request.POST['parameter']
      v = request.POST['value']

      if request.POST['location_group_id']:
        # Update
        location_group = Location_Group.objects.get(
          pk = request.POST['location_group_id'])

        if p == 'name':
          location_group.name = v

        if p == 'description':
          location_group.description = v

        if p == 'active':
          location_group.active = True if v == '1' else False

        location_group.save()

      else:
        # Insert
        location_group = Location_Group(
            name = request.POST.get('name', ''),
            description = request.POST.get('description', ''),
            active = request.POST.get('active', 1))
        location_group.save()

      # Set the device_id to pass back in the response.  This has the effect
      # of turning the 'add' form into an 'edit' form after the first save.
      response_data['data']['location_group_id'] = location_group.id

    except KeyError as ex:
      response_data['success'] = False
      response_data['message'] = ex.args[0]

  else:
    response_data['success'] = False
    response_data['message'] = 'Only POST via ajax is supported'

  return HttpResponse(json.dumps(response_data),
                      content_type = "application/json")


@csrf_exempt
def ajaxUpdateLocation(request):
  response_data = svenCommonAjaxData(request)

  if request.is_ajax() and request.method == 'POST':
    try:
      p = request.POST['parameter']
      v = request.POST['value']

      if request.POST['location_id']:
        # Update
        location = Location.objects.get(pk = request.POST['location_id'])

        if p == 'name':
          location.name = v

        if p == 'description':
          location.description = v

        if p == 'active':
          location.active = True if v == '1' else False

        location.save()

      else:
        # Insert
        if not request.POST['location_group_id']:
          raise KeyError(
            "Unable to add new location, location_group_id not passed")

        location_group = Location_Group.objects.get(
          pk = request.POST['location_group_id'])
        location = Location(name = request.POST.get('name', ''),
                            description = request.POST.get('description', ''),
                            active = request.POST.get('active', 1),
                            location_group = locationGroup)
        location.save()

      #
      # Set the device_id to pass back in the response.  This has the effect of turning the 'add' form into an 'edit' form after the first save
      #
      response_data['data']['location_id'] = location.id


    except KeyError as ex:
      response_data['success'] = False
      response_data['message'] = ex.args[0]

  else:
    response_data['success'] = False
    response_data['message'] = 'Only POST via ajax is supported'

  return HttpResponse(json.dumps(response_data),
                      content_type = "application/json")


# @todo This whole method is a fucked up mess.
@csrf_exempt
def ajaxUpdateDevice(request):
  response_data = svenCommonAjaxData(request)

  if request.is_ajax() and request.method == 'POST':
    try:
      p = request.POST['parameter']
      v = request.POST['value']

      if request.POST['device_id']:
        # Update
        device = Device.objects.get(pk = request.POST['device_id'])

        if p == 'name':
          device.name = v

        if p == 'description':
          device.description = v

        if p == 'active':
          device.active = True if v == '1' else False

        device.save()

      else:
        # Insert
        if not request.POST['location_id']:
          raise KeyError("Unable to add new device, location_id not passed")

        device = Device(name = request.POST.get('name', ''),
                        description = request.POST.get('description', ''),
                        active = request.POST.get('active', 1))
        device.save()

        location = Location.objects.get(pk = request.POST['location_id'])
        locationDevice = Location_Device(location = location, device = device)
        locationDevice.save()

      # Set the device_id to pass back in the response.  This has the effect of turning the 'add' form into an 'edit' form after the first save
      response_data['data']['device_id'] = device.id

      if p not in ['name', 'description', 'active']:
        if p == 'interface':
          # wipe all other parameters if the interface is being changed
          Device_Parameter.objects.filter(device = device).delete()

        if p == 'bus':
          # wipe all other parameters, except the interface, if the bus is being changed
          Device_Parameter.objects.filter(device = device).exclude(
            parameter = 'interface').delete()

        try:
          # Update existing parameter values if it exists
          parameter = Device_Parameter.objects.get(parameter = p,
                                                   device = device)
          parameter.value = v
          parameter.save()
        except:
          # Create new parameter since it doesn't exist
          Device_Parameter(parameter = p, value = v, device = device).save()

      response_data['data']['percentage_complete'] = calculatePercentageComplete(
        device, json.loads(request.POST['module_listing']))

    except:
      response_data['success'] = False

sven/apps/sensors/views.py
from django.shortcuts import render

def index( request ):
    data = { 'one' : 'elijah', 'two' : 'ethun', 'three' : 'ray' }

    return render( request, 'sensors/index.html', { 'datas' : data } )

sven/libs/display/views.py
from django.shortcuts import render

# Create your views here.

sven/libs/management/views.py
from django.shortcuts import render

# Create your views here.

sven/templates/monitor/device.html
{% extends "core/base.html" %}

{% block title %}Device Configuration{% endblock %}

{% block heading %}
  Device Configuration
  <span class="info-spot">
    <span class="icon-info-round"></span>
    <span class="info-bubble with-border" style="width: 200px;">
      <em><u>Devices</u></em>, Lorem Ipsum.
    </span>
  </span>
{% endblock %}

{% load staticfiles %}

{% block content %}

<div class="block anthracite-gradient glow clear-both margin-bottom margin-top">
  <form id="input_form" autocomplete="off">
  <input type="hidden" name="device_id" id="device_id" value="{{ device.id }}" />
  <input type="hidden" name="location_id" id="location_id" value="{{ location.id }}" />
  <input type="hidden" name="percentage_complete" id="percentage_complete" value="{{ pctComplete }}" />

  <h3 class="block-title">
    <a href="{{ base_url }}{% url 'monitor:locationGroup' location_group.id %}">{{ location_group.name }}</a> &raquo; <a href="{{ base_url }}{% url 'monitor:location' location.id %}">{{ location.name }}</a> &raquo; <span id="device_name">{{ device.name }}</span>

  <div class="button-group absolute-right">
    <!-- Active -->
    <span class="button-group margin-left">
      <label for="active-yes" class="button green-active {% if device.active == True %} active{% endif %}">
        <input type="radio" name="input_active" id="active-yes" value="1" {% if device.active == True %}checked{% endif %}>
        Active
      </label>
      <label for="active-no" class="button red-active {% if device.active == False %} active{% endif %}">
        <input type="radio" name="input_active" id="active-no" value="0" {% if device.active == False %}checked{% endif %}>
        Inactive
      </label>
    </span>

    <a href="#" class="button icon-pencil" id="edit-device-button">Edit</a>
    <a href="#" class="button icon-eye with-tooltip" id="view-history-button" title="History"></a>
    <a href="#" class="button icon-trash with-tooltip confirm" title="Delete"></a>
  </div>
  </h3>

  <div class="with-padding device-content-container" id="page-template-container" style="display: none;">
  {% if pageTemplate %}
      {% include pageTemplate %}
  {% endif %}
  </div>

  <div class="with-padding device-content-container" id="history-container" style="display: none;">
      History
  {{ history }}
  </div>

  <div class="with-padding device-content-container" style="display: none;" id="edit-device-container">
    <!-- Progress meter -->
    <div class="block with-padding large-margin-bottom">
      <h4>
        <span class="info-spot">
          <span class="icon-info-round"></span>
          <span class="info-bubble with-border" style="width: 200px;">
            When all parameters have been set successfully, this will be 100%
          </span>
        </span>
        Completion progress - <span id="percentage_complete_text">{{ pctComplete }}</span>%
      </h4>

      <span id="device_progress" class="margin-top margin-bottom"></span>
    </div>

    <!-- Name -->
    <label class="label">
      <span class="info-spot">
        <span class="icon-info-round"></span>
        <span class="info-bubble with-border" style="width: 200px;">
          Friendly name identifier
        </span>
      </span>
      Name
    </label><br />
    <input id="input_name" name="input_name" class="validate[required] input full-width margin-bottom" type="text" placeholder="Name" value="{{ device.name }}" />
    <br />

    <!-- Description -->
    <label class="label">
      <span class="info-spot">
        <span class="icon-info-round"></span>
        <span class="info-bubble with-border" style="width: 200px;">
          Description
        </span>
      </span>
      Description
    </label>

    <textarea id="input_description" name="input_description" class="validate[required] input full-width margin-bottom" placeholder="Description">{{ device.description }}</textarea>
    <br />

    <!-- Interface -->
    <label>
      <span class="info-spot">
        <span class="icon-info-round"></span>
        <span class="info-bubble with-border" style="width: 200px;">
          Interface type info
        </span>
      </span>
      Interface
    </label><br />

    <select class="select check-list" name="input_interface">
      {% if not interface %}
      <option>Choose an interface</option>
      {% endif %}
    </select>

    <br /><br />
    <div id="bus-selection" class="margin-bottom" style="display: none">
      <!-- Bus -->
      <label>
        <span class="info-spot">
          <span class="icon-info-round"></span>
          <span class="info-bubble with-border" style="width: 200px;">
            Bus type info
          </span>
        </span>
        Bus
      </label><br />

      <select class="select check-list" name="input_bus">
        {% if not bus %}
        <option selected>Choose a bus</option>
        {% endif %}
      </select>
    </div>
    <div id="bus-components"></div>
  </div>

  <div class="with-padding">
    <br />
    <a id="testDeviceCallback" class="button margin-right">
      <span class="button-icon green-gradient glossy"><span class="icon-star"></span></span>
      Test
    </a>

    <a href="{{ base_url }}{% url 'monitor:location' location.id %}" class="button margin-right edit_location_save">
      <span class="button-icon blue-gradient glossy"><span class="icon-like"></span></span>
      Finished
    </a>
  </div>
  </form>
</div>

<script src="{% static 'js/monitor/common.js' %}"></script>
<script src="{% static 'js/monitor/device.js' %}"></script>

<script type="text/javascript">
  $(function() {
    $('.global_module_listing').change( function() {
      $.each(module_listing, function (key, values) {
        if (values.modules.length > 0) {
          $('select[name=input_interface]').append('<option value="' + key + '" ' + ( key == '{{ interface }}' ? 'selected' : '' ) + '>' + key + '</option>');

          if (key == '{{ interface }}') {
            $.each(values.modules, function (module_key, module_value) {
              $('select[name=input_bus]').append('<option value="' + module_value.module + '" ' + ( module_value.module == '{{ bus }}' ? 'selected' : '' ) + '>' + module_value.meta.name + '</option>');
            });

            $('select[name=input_bus]').trigger('silent-change');

            $('#bus-selection').show();
          }
        }
      });

      $('select[name=input_interface]').trigger('silent-change');

      {% if interface and bus %}
        $('#bus-components').load('/monitor/ajaxInputMatrix', { 'interface': '{{ interface }}', 'bus': '{{ bus }}', 'device_id': $('#device_id').val(), 'module_listing': JSON.stringify(getModulesForSelectedInterface()) });
      {% endif %}
    });
  });


  {% if pageTemplate %}
    $('#page-template-container').show();
  {% else %}
    $('#edit-device-container').show();
  {% endif %}

  $('#edit-device-button').click(function () {
    $('.device-content-container').hide();

    if ($(this).hasClass('active')) {
      $(this).removeClass('blue-active active');
      {% if pageTemplate %}
        $('#page-template-container').show();
      {% else %}
        $('#history-container').show();
      {% endif %}
    }
    else {
      $('#view-history-button').removeClass('blue-active active');
      $(this).addClass('blue-active active');
      $('#edit-device-container').show();
    }
  });

  $('#view-history-button').click(function () {

    if ($(this).hasClass('active')) {
      $(this).removeClass('active blue-active');

      {% if pageTemplate %}
        $('.device-content-container').hide();
        $('#page-template-container').show();
      {% endif %}
    }
    else {
      $('#edit-device-button').removeClass('blue-active active');
      $('.device-content-container').hide();
      $(this).addClass('active blue-active');
      $('#history-container').show();
    }
  });
</script>

{% endblock %}

{% block footer %}{%  endblock %}

sven/templates/monitor/deviceList.html
<h3 class="margin-left">Devices in <em>{{ location.name }}</em></h3>

<table class="simple-table responsive-table" id="table-data-container">
    <thead>
        <tr>
            <th scope="col"><input type="checkbox" name="check-all" id="check-all" value="1"></th>
            <th scope="col" style="width: 110px">Action</th>
            <th scope="col">Name</th>
            <th scope="col" class="hide-on-mobile" style="width: 100px;">Last Updated</th>
            <th scope="col" style="width: 180px">Alarm Status</th>
            <th scope="col" style="width: 90px;">Active</th>
        </tr>
    </thead>

    <tfoot>
        <tr>
            <td colspan="6">
                &nbsp;&nbsp;&nbsp;
                <a href="{{ base_url }}{% url 'monitor:deviceNew' %}" class="button margin-right margin-left edit_location_save">
                    <span class="button-icon green-gradient glossy"><span class="icon-plus"></span></span>
                    Add New Device
                </a>

                <form method="post" id="devices_action_post" action="" style="float:left;">
                With selected:
                <select name="actions" id="group_actions" class="select  mid-margin-left">
                    <option value="delete">Delete</option>
                    <option value="duplicate">Duplicate</option>
                    <option value="activate">Activate</option>
                    <option value="deactivate">Deactivate</option>
                    <option value="trash">Move to trash</option>
                </select>
                <button type="submit" id="actions_submit" class="button">Go</button>
                </form>
            </td>
        </tr>
    </tfoot>

    <tbody>
        {% for object in location.location_device_set.all %}
        <tr class="locationsRow">
            <th scope="row" class="checkbox-cell"><input type="checkbox" name="locations_checked[]" value="{{ object.device.id }}"></th>
            <td class="locationsRowActionCell">
                <a href="{{ base_url }}{% url 'monitor:device' id=object.device_id %}" class="button margin-right edit_location_save">
                    <span class="button-icon orange-gradient glossy"><span class="icon-pencil"></span></span>
                    View
                </a>
            </td>
            <td class="locationsRowActionCell">{{ object.device.name }}</td>
            <td class="locationsRowActionCell hide-on-mobile">{{ object.device.updated|date:'G:i - n/j/y' }}</td>
            <td class="locationGroupRowActionCell">
                <span class="button-group">
                    <label for="alarm-system-device-1-{{ object.id }}" class="button green-active">
                        <input type="radio" name="alarm-system-device-{{ object.id }}" id="alarm-system-device-1-{{ object.id }}" class="alarm-system-device" value="1" {% if object.device.arm_status_device_set.all.0.arm_status_id == 1 %}checked{% endif %}>
                        Away
                    </label>
                    <label for="alarm-system-device-2-{{ object.id }}" class="button green-active">
                        <input type="radio" name="alarm-system-device-{{ object.id }}" id="alarm-system-device-2-{{ object.id }}" class="alarm-system-device" value="2" {% if object.device.arm_status_device_set.all.0.arm_status_id == 1 %}checked{% endif %}>
                        Home
                    </label>
                    <label for="alarm-system-device-3-{{ object.id }}" class="button green-active">
                        <input type="radio" name="alarm-system-device-{{ object.id }}" id="alarm-system-device-3-{{ object.id }}" class="alarm-system-device" value="3" {% if object.device.arm_status_device_set.all.0.arm_status_id == 3 %}checked{% endif %}>
                        Night
                    </label>
                </span>
            </td>
            <td>
                <span class="button-group">
                    <label for="active-{{ object.device.id }}-yes" class="button green-active {% if object.device.active == True %} active{% endif %}">
                        <input type="radio" class="device_active_state" rel="{{object.device.id}}" name="radio-buttons-{{ object.device.id }}" id="active-{{ object.device.id }}-yes" value="1" {% if object.device.active == True %}checked{% endif %}>
                        Yes
                    </label>
                    <label for="active-{{ object.device.id }}-no" class="button red-active {% if object.device.active == False %} active{% endif %}">
                        <input type="radio" class="device_active_state" rel="{{object.device.id}}" name="radio-buttons-{{ object.device.id }}" id="active-{{ object.device.id }}-no" value="0" {% if object.device.active == False %}checked{% endif %}>
                        No
                    </label>
                </span>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>

sven/templates/monitor/inputMatrix.html
{{ message }}

sven/templates/monitor/location.html
{% extends "core/base.html" %}

{% block title %}Location Configuration{% endblock %}

{% block heading %}
    Location Configuration
    <span class="info-spot">
        <span class="icon-info-round"></span>
        <span class="info-bubble with-border" style="width: 200px;">
            <em><u>Locations</u></em>, such as 'Kitchen', 'Living Room' or 'Garage' encapsulate your monitored / controlled sensors and automation tasks.
        </span>
    </span>

{% endblock %}

{% load staticfiles %}

{% block content %}
<div class="block anthracite-gradient glow clear-both margin-top">
    <form id="input_form" autocomplete="off">
    <input type="hidden" name="location_group_id" id="location_group_id" value="{{ locationGroup.id }}" />
    <input type="hidden" name="location_id" id="location_id" value="{{ location.id }}" />

    <h3 class="block-title">
        <a href="{{ base_url }}{% url 'monitor:locationGroup' location_group.id %}">{{ location_group.name }}</a> &raquo; <span id="location_name">{{ location.name }}</span>

        <!-- Active -->
        <span class="button-group float-right">
            <label for="active-yes" class="button green-active {% if location.active == True %} active{% endif %}">
                <input type="radio" name="input_active" id="active-yes" value="1" {% if location.active == True %}checked{% endif %}>
                Active
            </label>
            <label for="active-no" class="button red-active {% if location.active == False %} active{% endif %}">
                <input type="radio" name="input_active" id="active-no" value="0" {% if location.active == False %}checked{% endif %}>
                Inactive
            </label>
        </span>
    </h3>
{{ sess.description }}
    <div class="with-padding">

        <!-- Name -->
        <label class="label">
            <span class="info-spot">
                <span class="icon-info-round"></span>
                <span class="info-bubble with-border" style="width: 200px;">
                    Friendly name identifier
                </span>
            </span>
            Name
        </label><br />
        <input id="input_name" name="input_name" class="validate[required] input full-width margin-bottom" type="text" placeholder="Name" value="{{ location.name }}" />
        <br />

        <!-- Description -->
        <label class="label">
            <span class="info-spot">
                <span class="icon-info-round"></span>
                <span class="info-bubble with-border" style="width: 200px;">
                    Description
                </span>
            </span>
            Description
        </label>
        <textarea id="input_description" name="input_description" class="validate[required] input full-width margin-bottom" placeholder="Description">{{ location.description }}</textarea>
    </div>
    </form>

    <div class="with-padding" id="table_data_container"></div>

    <div class="with-padding">
        <a href="{{ base_url }}{% url 'monitor:locationGroup' location_group.id %}" class="button margin-right edit_location_save">
            <span class="button-icon blue-gradient glossy"><span class="icon-like"></span></span>
            Finished
        </a>
    </div>

</div>


<script src="{% static 'js/monitor/common.js' %}"></script>
<script src="{% static 'js/monitor/location.js' %}"></script>

{% endblock %}

{% block footer %}

{%  endblock %}